language: cpp
sudo: required
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - g++-5
        - libblas-dev
        - liblapacke-dev
    env: CXX_COMPILER='g++-5'
script:
- cmake
  -H.
  -Bbuild
  -DCMAKE_CXX_COMPILER=${CXX_COMPILER}
  -DCMAKE_BUILD_TYPE=Release
  -DCBLAS_INCLUDE_DIR=/usr/include
  -DCBLAS_LIBRARIES=/usr/lib/libblas
  -DLAPACKE_INCLUDE_DIR=/usr/include
  -DLAPACKE_LIBRARIES=/usr/lib/
- cd build && make
- ctest
- cd -
after_failure:
- cat Testing/Temporary/LastTest.log
